version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
os: Visual Studio 2015
clone_depth: 50
install:
- cmd: '"C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64'
build_script:
- cmd: >-
    mkdir build

    cd build

    cmake ..

    nmake
